repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
        additional_dependencies: ["ruff==0.12.8"]
        files: ^api/
      - id: ruff-format
        additional_dependencies: ["ruff==0.12.8"]
        files: ^api/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace


