# docker-compose.yaml

services:
  api:
    image: api:latest
    container_name: api
    # ports:
    #   - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always

  nginx:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./volume/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volume/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      api:
        condition: service_healthy
    restart: always
