name: Build and Push

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  ALIYUN_REGISTRY: ${{ vars.ALIYUN_REGISTRY }}
  ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}
  ALIYUN_REGISTRY_PWD: ${{ secrets.ALIYUN_REGISTRY_PWD }}
  API_IMAGE_NAME: ${{ vars.API_IMAGE_NAME }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      workflow: ${{ steps.filter.outputs.workflow }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check for file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.event.before }}
          filters: |
            api:
              - 'api/**'
            web:
            workflow:
              - '.github/workflows/**'

  api-build-and-push:
    runs-on: ubuntu-latest
    needs: [changes]
    if: needs.changes.outputs.api == 'true' || needs.changes.outputs.workflow == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ env.ALIYUN_REGISTRY_USER }}
          password: ${{ env.ALIYUN_REGISTRY_PWD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.ALIYUN_REGISTRY }}/${{ env.API_IMAGE_NAME }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v6
        with:
          context: api
          push: true
          file: api/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}