name: Only Build API

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      api-changed: ${{ steps.changes.outputs.api }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          base: main
          filters: |
            api:
              - 'api/**'

  api-build:
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: No API changes detected
        if: needs.check-changes.outputs.api-changed != 'true'
        run: |
          echo "🎯 No changes detected in API directory, skipping Docker image build"
          echo "📁 Scope checked: api/**"
          echo "✅ No build required, task completed"

      - name: Set up Docker Buildx
        if: needs.check-changes.outputs.api-changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker image
        if: needs.check-changes.outputs.api-changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: api
          push: false
          file: api/Dockerfile
          tags: api:local
          platforms: linux/amd64

      - name: API build completed
        if: needs.check-changes.outputs.api-changed == 'true'
        run: |
          echo "🚀 API Docker image build completed"
          echo "📦 Image tag: api:local"
