name: Python Style

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  python-style:
    name: Python Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            api/**
            .github/workflows/style.yml

      - name: Setup Python
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pip install ruff==0.12.8

      - name: Ruff check
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          ruff --version
          ruff check ./api
          ruff format --check ./api

      - name: Lint hints
        if: failure()
        run: |
          echo '请运行: ruff check --fix ./api && ruff format ./api 来自动修复可修复的问题。'
          echo '若仍有未修复的问题，请根据 Ruff 的输出逐项手动修复剩余问题。'
